aisco.financialreport.core=aisco.financialreport.core
aisco.financialreport.income=aisco.financialreport.income
aisco.financialreport.expense=aisco.financialreport.expense
aisco.financialreport.frequency=aisco.financialreport.frequency
aisco.program.activity=aisco.program.activity
aisco.program.operational=aisco.program.operational 
aisco.donation.payment.gateway=aisco.donation.payment.gateway
aisco.financialreport.incomewithfrequency=aisco.financialreport.income,aisco.financialreport.frequency
aisco.financialreport.expensewithfrequency=aisco.financialreport.expense,aisco.financialreport.frequency